In [16]:
import sys,os

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import classification_report

In [17]:
__script_path=os.path.abspath(globals().get('__file__','.'))
__script_dir = os.path.dirname(__script_path)
root_dir = os.path.abspath(f'{__script_dir}')
print(root_dir)
for lib in [root_dir][::-1]:
    if lib in sys.path:
        sys.path.remove(lib)
    sys.path.insert(0,lib)
from scripts.path_configs import *

/home/dinhtanloc/Projects/loan_ml_prediction_system

In [18]:
df=pd.read_csv(f'{data_dir}/loan_data.csv')

tar_column='loan_status'
Num_col=df.select_dtypes('number').columns.tolist()[:-1]
Cat_col=df.select_dtypes('object').columns.tolist()
print(f"Numeric columns: {len(Num_col)} and Categorical columns: {len(Cat_col)}")
df

Numeric columns: 8 and Categorical columns: 5

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

# **2. Data Preprocessing**

In [19]:
df[Cat_col][:20]

,person_gender,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file
0,female,Master,RENT,PERSONAL,No
1,female,High School,OWN,EDUCATION,Yes
2,female,High School,MORTGAGE,MEDICAL,No
3,female,Bachelor,RENT,MEDICAL,No
4,male,Master,RENT,MEDICAL,No
5,female,High School,OWN,VENTURE,No
6,female,Bachelor,RENT,EDUCATION,No
7,female,High School,RENT,MEDICAL,No
8,female,Associate,RENT,PERSONAL,No
9,female,High School,OWN,VENTURE,No
10,female,High School,RENT,VENTURE,No
11,female,Associate,OWN,HOMEIMPROVEMENT,No
12,male,Bachelor,RENT,VENTURE,No
13,male,Master,RENT,EDUCATION,No
14,female,Associate,RENT,EDUCATION,No
15,female,Master,MORTGAGE,DEBTCONSOLIDATION,Yes
16,male,Bachelor,RENT,EDUCATION,No
17,female,High School,RENT,MEDICAL,No
18,male,Bachelor,RENT,DEBTCONSOLIDATION,No
19,female,Master,MORTGAGE,EDUCATION,No

In [20]:
for col in Cat_col:
  print(f'{col}: {df[col].nunique()}')

person_gender: 2
person_education: 5
person_home_ownership: 4
loan_intent: 6
previous_loan_defaults_on_file: 2

In [21]:
le=LabelEncoder()
for col in Cat_col:
  df[col]=le.fit_transform(df[col])

In [22]:
row_values = df.iloc[3].tolist()  
print(row_values)

[23.0, 0.0, 1.0, 79753.0, 0.0, 3.0, 35000.0, 3.0, 15.23, 0.44, 2.0, 675.0, 0.0, 1.0]

In [23]:
pipe = Pipeline([ ('ss', StandardScaler()) ])

In [24]:
df_ss=df.copy()

In [25]:
df_ss[Num_col]=pipe.fit_transform(df_ss[Num_col])

In [26]:
x_train, x_test, y_train, y_test = train_test_split(df_ss.drop(columns=tar_column,axis=1), df_ss[tar_column], test_size=0.2, random_state=42)

In [27]:
df_ss.to_csv(f"{exps_dir}/processed_loan_data.csv", index=None)
x_train.to_csv(f"{exps_dir}/x_train.csv", index=None)
x_test.to_csv(f"{exps_dir}/x_test.csv", index=None)
y_train.to_csv(f"{exps_dir}/y_train.csv", index=None)
y_test.to_csv(f"{exps_dir}/y_test.csv", index=None)